# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: helloworld.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "helloworld.HelloRequest" do
    optional :name, :string, 1
  end
  add_message "helloworld.Metodo1Request" do
  end
  add_message "helloworld.Metodo2Request" do
    optional :value, :float, 1
  end
  add_message "helloworld.Metodo3Request" do
    optional :value1, :float, 1
    optional :value2, :float, 2
    optional :value3, :float, 3
    optional :value4, :float, 4
    optional :value5, :float, 5
    optional :value6, :float, 6
    optional :value7, :float, 7
    optional :value8, :float, 8
  end
  add_message "helloworld.Metodo4Request" do
    optional :text, :string, 1
  end
  add_message "helloworld.Metodo5Request" do
    optional :object, :string, 1
  end
  add_message "helloworld.HelloReply" do
    optional :message, :string, 1
  end
  add_message "helloworld.Metodo1Reply" do
  end
  add_message "helloworld.Metodo2Reply" do
    optional :message, :string, 1
  end
  add_message "helloworld.Metodo3Reply" do
    optional :message, :string, 1
  end
  add_message "helloworld.Metodo4Reply" do
    optional :message, :string, 1
  end
  add_message "helloworld.Metodo5Reply" do
    optional :message, :string, 1
  end
end

module Helloworld
  HelloRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("helloworld.HelloRequest").msgclass
  Metodo1Request = Google::Protobuf::DescriptorPool.generated_pool.lookup("helloworld.Metodo1Request").msgclass
  Metodo2Request = Google::Protobuf::DescriptorPool.generated_pool.lookup("helloworld.Metodo2Request").msgclass
  Metodo3Request = Google::Protobuf::DescriptorPool.generated_pool.lookup("helloworld.Metodo3Request").msgclass
  Metodo4Request = Google::Protobuf::DescriptorPool.generated_pool.lookup("helloworld.Metodo4Request").msgclass
  Metodo5Request = Google::Protobuf::DescriptorPool.generated_pool.lookup("helloworld.Metodo5Request").msgclass
  HelloReply = Google::Protobuf::DescriptorPool.generated_pool.lookup("helloworld.HelloReply").msgclass
  Metodo1Reply = Google::Protobuf::DescriptorPool.generated_pool.lookup("helloworld.Metodo1Reply").msgclass
  Metodo2Reply = Google::Protobuf::DescriptorPool.generated_pool.lookup("helloworld.Metodo2Reply").msgclass
  Metodo3Reply = Google::Protobuf::DescriptorPool.generated_pool.lookup("helloworld.Metodo3Reply").msgclass
  Metodo4Reply = Google::Protobuf::DescriptorPool.generated_pool.lookup("helloworld.Metodo4Reply").msgclass
  Metodo5Reply = Google::Protobuf::DescriptorPool.generated_pool.lookup("helloworld.Metodo5Reply").msgclass
end
