# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: rpcmodel.proto for package 'rpcm'

require 'grpc'
require 'rpcmodel_pb'

module Rpcm
  module Greeter
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'rpcm.Greeter'

      rpc :Metodo1, Metodo1Request, Metodo1Reply
      rpc :Metodo2, Metodo2Request, Metodo2Reply
      rpc :Metodo3, Metodo3Request, Metodo3Reply
      rpc :Metodo4, Metodo4Request, Metodo4Reply
      rpc :Metodo5, Metodo5Request, Metodo5Reply
    end

    Stub = Service.rpc_stub_class
  end
end
